# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "uhl,steine,scherben"
email: "uhl.christian@googlemail.com"
description: "uhl, steine scherben ist ein Podcast über die Erfahrungen von Christian in der Rolle eines Head of Engineering"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://uhl-steine-scherben.org" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: chrisuhl
github_username:  christianuhlcc
header_image: /assets/images/autoweirdfm_logo_269x100_lightbg.png

# Podcast rss feed configuration
podcast_url: https://christianuhlcc.github.io
podcast_album_art: /assets/images/logo_1400x1400.png
podcast_title: "uhl, steine, scherben"
podcast_owner: "Christian Uhl"
podcast_email: "uhl.christian@googlemail.com"
podcast_category: "Technology"
podcast_explicit: "yes"
podcast_author: "Christian Uhl"
podcast_description: Regelmäßiger Podcast rund um die Erfahrungen von Christian in seiner neuen Rolle als Head of Engineering.
podcast_summary: Regelmäßiger Podcast rund um die Erfahrungen von Christian in seiner neuen Rolle als Head of Engineering.
podcast_subtitle: plötzlich Manager, was tun?

url: "https://uhl-steine-scherben.org"

# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes"

# Theme settings
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      read_time: false
      comments: true
      share: true
      related: true
      author_profile: true

# Site Author
author:
  name             : "Christian Uhl"
  avatar           : "/assets/images/avatar.jpg"
  bio              : "Developer, craftsperson and occasional idiot. Senior Engineering Manager at Personio. Endurance runner, climber and cyclist."
  location         : "München"
  github           : "christianuhlcc"
  linkedin         : "christian-uhl-957a61151"
  twitter          : "chrisuhl"
  xing             : "https://www.xing.com/profile/Christian_Uhl14"
  link             : "https://uhl-steine-scherben.org/blog/"

exclude:
  - Gemfile
  - Gemfile.lock
plugins:
  - jekyll-sitemap
  - jekyll-feed 
  - jekyll-include-cache